### ISSUE TITLE
[Discussion] Multiple TLSA records based on host listed in SubjectAltName

### ISSUE THREAD

**Issue by Glandos** [plinss/bindtool#2]
I developped a small wrapper around [hash-slinger tlsa tool](https://github.com/letoams/hash-slinger/blob/master/tlsa), that extract iterates on `subjectAltName` to generate all `TLSA` records at once:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import imp

from M2Crypto import X509

tlsa = imp.load_source('tlsa', '/usr/bin/tlsa')


def print_tlsa(chain, args):
    tlsa.genRecords(args.host, args.protocol, args.port, chain,
                    args.output, args.usage, args.selector, args.mtype)


def get_subject_alternative_names(certificate):
    cert = X509.load_cert(certificate)
    return [name[4:] if name.startswith('DNS:') else name
            for name in cert.get_ext('subjectAltName').get_value().split(', ')]


class Args(object):
    pass


if __name__ == '__main__':

    args = Args()

    args.certificate = sys.argv[1]
    args.port = int(sys.argv[2])
    args.debug = False

    chain, verify_result = tlsa.getLocalChain(args.certificate, args.debug)

    args.output = 'rfc'
    args.protocol = 'tcp'
    args.usage = 3
    args.selector = 0
    args.mtype = 2

    for host in get_subject_alternative_names(args.certificate):
        args.host = host
        print_tlsa(chain, args)
```

As you can see, this is a hack. I was wondering if the idea of loading hostnames from the certificate file itself would be a good addition to `bindtool`?

Proposed syntax: `{{tlsa_multi:port:cert_file:usage:selector:proto:ttl:type:pass}}`

The `host` parameter will be gone.

Note that I used `M2` crypto module to avoid forking a lot of `openssl`. I can totally understand the avoidance of external dependencies, but it is also possible to require `M2` only for `tlsa_multi` records. Obviously, the dependency to `hash-slinger` will be gone.

**Comment by plinss** [comment]
Interesting idea, should be easy to add

**Comment by plinss** [comment]
Added in b8e99123bf355424156d2714b743db87ce3f0d9e
