### ISSUE TITLE
Include parameters

### ISSUE THREAD

**Issue by Glandos** [plinss/bindtool#3]
For now, I'm using a lot the include feature to define hostnames in the same zone:
```
{{subhost=www}}
{{include:example.d/subhost}}
```
With `example.d/subhost`:
```
{{subhost}}     IN A {{ip4}}
        IN AAAA {{net6}}::2
```

I'd find useful a shorter syntax like this:
```
{{include:example.d/subhost:subhost=www}}
```

With a general syntax:
```
{{include:filename:param1=value1:…:paramN=valueN}}
```
Of course, there are some limitations. Filenames and parameter values won't be able to contains `:` for example. But I think it fits in the current design, without adding too much complexity.

Parameters should be local to the include if possible, but the current code does not allow this.

**Comment by plinss** [comment]
Added in c20577df6473d667c1ae1695739fd1f8c3f109c6, please give it a test and I'll update the readme and issue a release later if it's all good. 

Parameters are local to the include (but do get passed to nested includes), variables can still be set in the include and they propagate back up (I use includes to set common variables so I don't want to lose that).

Note that you can have : and = in values, you just need to either quote the value or escape the colon or equals with a backslash, e.g. {{include:file:foo="foo:bar":bar=bar\:foo}}

**Comment by Glandos** [comment]
That's perfect. And there's even quoting and escaping. Very nice :+1: 

But if you always work so fast, I'll get use to it. Be careful!
