### ISSUE TITLE
Included files are relative to the zone_file, not the current one

### ISSUE THREAD

**Issue by Glandos** [plinss/bindtool#4]
The `README.md` specifies that:
>The file path is relative to the path of the file containing the `include` command or the configured `include` directory.

However, this seems to be a wrong statement, in the case of nested includes. It seems that the path is relative to the original zone file, and not the current file.

I don't have any issue with the current behavior. Other softwares have the same (e.g. nginx), but then, the documentation is not accurate.

**Comment by plinss** [comment]
That's a regression, it used to be relative to the file containing the include. I must have broken it when I refactored the directory handling.

**Comment by plinss** [comment]
fixed by 7b0405708c68ee2ffda46960430d2bfd1fe930a9

**Comment by Glandos** [comment]
So now, we also have the ability to declare relative files from the primary zone file or the current file. That's nice, thanks.

**Comment by plinss** [comment]
Yeah, it was easy to add and this way if anyone was relying on the zone file relative path it should still work. It tests current file relative, zone file relative, and then configured include directory in that order, first one found wins.
